name: publish SmartEnum.Dapper to nuget
on:
  workflow_dispatch:
  push:
    branches:
      - main # Your default release branch
    paths:
      - 'src/SmartEnum.Dapper/**'
jobs:
  publish:
    name: list SmartEnum.Dapper on nuget.org
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Required for a specific dotnet version that doesn't come with ubuntu-latest / windows-latest
      # Visit bit.ly/2synnZl to see the list of SDKs that are pre-installed with ubuntu-latest / windows-latest
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: |
              6.0.x
              7.0.x
              8.0.x
      
      # Publish
      - name: publish on version change
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: src/SmartEnum.Dapper/SmartEnum.Dapper.csproj # Relative to repository root
          VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          TAG_COMMIT: true # Flag to enable / disable git tagging
          TAG_FORMAT: SmartEnumDapper-v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
